### PR TITLE
🚨 Add lint action

### PR DESCRIPTION
**Pull request by dragonDScript**
#106

### CODE REVIEW

**Comment by lostdesign** [comment]
Thanks, I am unsure what it will do just now? Prettier I think can be removed and only eslint may be used, since prettier screwed up certain formatting lol. What eslint config will it use? The one from the project?

**Comment by dragonDScript** [comment]
> Thanks, I am unsure what it will do just now? Prettier I think can be removed and only eslint may be used, since prettier screwed up certain formatting lol. What eslint config will it use? The one from the project?

The one in package.json. I need to test it, I don't know if it will work. If prettier messes things up, why not remove it?

**Comment by lostdesign** [comment]
I am unsure about the whole setup. Closing this until its clear.

**Comment by dragonDScript** [comment]
Okay, what's wrong with it?

**Comment by lostdesign** [comment]
No need for it now because I'm unsure how to handle it.

**Comment by dragonDScript** [comment]
Okay fine

**Comment by lostdesign** [comment]
Will reconsider later, but thank you for your contribution.

**Pull request closed without merging**
